# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e57bb6daa20a80589ee7993b3df5223cfdafd38949938a0fa6484634e0dbc09a910f4ec8455eacd9c11e04b12cb6f970707aab1564e9bc904af730f0b5f70098

test:
  secret_key_base: 6b3e8e86d1c0ac39caa2273c2791c5a253ab0ddd0126dd49ecbaa55ee557a9b71c7c97ab397f9ba0663bbbbd6d3e32ff3ebc9810d9aed6801900fc4316162782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
